directories:
  output: .
  buildResources: build
appId: com.vpm.tracker
productName: VPM Tracker
win:
  target:
    target: nsis
    arch:
      - x64
  artifactName: VPM-Tracker-Setup.exe
compression: maximum
publish:
  provider: github
  owner: ammar-dev-dev
  repo: vpm-tracker
extraMetadata:
  main: electron.cjs
files:
  - filter:
      - dist/**/*
      - electron.cjs
      - public/**/*
asar: true
electronVersion: 42.3.3
